Lesson9 review branc
podolyanbogdan/login pull request #12
Opened 2022-07-28 11:22 UTC by podolyanbogdan

2022-07-28 11:25 UTC, podolyanbogdan commented
Balloon на Тулбар и обводку выбраного цвета в recycler не успел сделать

2022-07-29 12:15 UTC, shadwork requested changes
молодцом - есть что переписать

2022-07-29 12:15 UTC, shadwork commented on .idea/misc.xml
>          <entry key="..\:/Users/kvtvnv/AndroidStudioProjects/login/app/src/main/res/drawable/dialog_corners.xml" value="0.1825" />
да удали ты уже этот файл из репозитория!

2022-07-29 12:15 UTC, shadwork commented on app/src/main/java/com/example/login/data/NoteColors.kt
> +    Red(R.color.red),
Не нужно опираться на целые числа взятые из андроид ресурсов

2022-07-29 12:15 UTC, shadwork commented on app/src/main/java/com/example/login/room/NoteDao.kt
> +    @Query(
lets simplify the sorting

2022-07-29 12:15 UTC, shadwork commented on app/src/main/java/com/example/login/room/NoteEntity.kt
> +    @ColumnInfo(name = "isExpanded")
isExpanded should be not stored in db

2022-07-29 12:15 UTC, shadwork commented on app/src/main/java/com/example/login/ui/addNote/AddNoteViewModel.kt
> +    val titleValue: MutableLiveData<String> = MutableLiveData()
just create a model and collecting the data with databinding

2022-07-29 12:15 UTC, shadwork commented on app/src/main/java/com/example/login/ui/emergency/EmergencyDialog.kt
> +        binding.btnYes.setOnClickListener {
rewrite with navigation and injected database

2022-07-29 12:15 UTC, shadwork commented on app/src/main/res/drawable/ic_menu_gallery.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
why this file needed

2022-07-29 20:16 UTC, podolyanbogdan commented
весь день был занят увы, все что успел вот

2022-08-01 08:50 UTC, merged