Lesson11 review branch
podolyanbogdan/login pull request #14
Opened 2022-08-11 13:08 UTC by podolyanbogdan

2022-08-12 06:27 UTC, shadwork requested changes
good

2022-08-12 06:27 UTC, shadwork commented on app/src/main/java/com/example/login/repository/ImageRepository.kt
> +    private val matrix2 = ColorMatrix(
should be array

2022-08-12 16:11 UTC, podolyanbogdan commented on app/src/main/java/com/example/login/repository/ImageRepository.kt
> +    private val matrix2 = ColorMatrix(
done

2022-08-16 07:56 UTC, shadwork approved these changes

2022-08-16 07:57 UTC, merged